### ISSUE TITLE
Tapping on iOS 12 doesn't work properly with multiple line labels

### ISSUE THREAD

**Issue by dbard** [matteobortolazzo/HtmlLabelPlugin#106]
If the user taps on a link appearing after the first line of a multiple line label, the link doesn't open.  I was able to reproduce this using the test project with the Nuget.

I've put up a pull request with what I think is a good solution.  https://github.com/matteobortolazzo/HtmlLabelPlugin/pull/105

And... thank you for your work on this Nuget!!

**Comment by IeuanWalker** [comment]
@matteobortolazzo is this fixed? I have a bug in our app that neds fixing today, if there is a fix any chance of a beta or preview release today?

**Comment by matteobortolazzo** [comment]
@IeuanWalker I cannot test it so I trust @dbard PR
Now 4.1.3 is releasing

**Comment by IeuanWalker** [comment]
@matteobortolazzo  thanks for releasing it so quickly. Unfortunately version 4.1.3 still doesn't work for me. I'm using a iOS 13.5 emulator.

**Comment by matteobortolazzo** [comment]
I am sorry to head that!

Unfortunately I cannot work on that right now.

Can you please try version 5 (alpha) then?

**Comment by IeuanWalker** [comment]
@matteobortolazzo i can confirm link and phone numbers are working, but email link isn't.
Also seams to have an issue with scrolling.

The control is wrapped in a scrollview, but is only scrollable when the view is refreshed with hot reload. Wasnt an issue on older versions

**Comment by matteobortolazzo** [comment]
Got it, can add those issues as comments in pr #104 please?

**Comment by IeuanWalker** [comment]
@matteobortolazzo done. As i need this fixed my self are you ok with me messing around with that PR? cant promise anything though.

**Comment by matteobortolazzo** [comment]
Sure, help is always welcome :) thanks

**Comment by dbard** [comment]
Note that the code I provided was meant to address that there was some unnecessary math being performed to determine total characters which wasn't necessary.  It only addressed where on the screen a tap occurred, nothing to do with what happens within the library after the tap was correctly observed.

**Comment by matteobortolazzo** [comment]
@dbard sure, don't worry, your update is still valid! Thanks again

**Comment by IeuanWalker** [comment]
@matteobortolazzo @dbard 
The scroll issue seams to happen if the html is set after the the page is loaded.
In my project I have a markdown file embedded in the project, and in the OnAppearing of the page i read the file, and convert it too html, then set the text on HtmlLabel. I've replicated the issue here - https://github.com/IeuanWalker/HtmlLabelPlugin/tree/Bug/Scrollview

The scrollview works just text is cut off

And this is the error that I'm getting when clicking the email link (also replicated in the above repo)
```
2020-06-24 18:02:29.112257+0100 HtmlLabel.Forms.Plugin.Tests.App.iOS[62636:1277100] -canOpenURL: failed for URL: "mailto:" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
[0:] Specified method is not supported.:             ERROR: 
2020-06-24 18:02:29.121559+0100 HtmlLabel.Forms.Plugin.Tests.App.iOS[62636:1277258] [default] Failed to open URL mailto:github@github.com?subject=Awesome&body=Awesome%20plugin: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=247, _LSFunction=-[_LSDOpenClient openURL:options:completionHandler:]}
```

**Comment by matteobortolazzo** [comment]
Got it, glad to hear. About emails, it looks like it is a `Xamarin.Essentials` issue, do you need to whitelist emails in the Info.plist maybe?

**Comment by IeuanWalker** [comment]
@matteobortolazzo Ye sure ill give it a test in a bit

**Comment by IeuanWalker** [comment]
@matteobortolazzo email is working fine.

I use a simulator 90%, but turns out the Xamarin.Essentials email isn't supported on iOS simulators.
From the docs - _'To use the Email API on iOS you must run it on a physical device, else an exception will be thrown.'_
https://docs.microsoft.com/en-us/xamarin/essentials/email?tabs=ios

Tested my project on a physical device and I'm getting a 'NullReferenceException' when clicking on an email link. I've imported the HtmlLabel project into mine _(so I don't have to create provisioning profile to test on a physical device)_ and its throwing the error here - 
![image](https://user-images.githubusercontent.com/6544051/85698129-48439f00-b6d2-11ea-8d18-9f60cf33f2fe.png)

Update the code to this fixes it - 
![image](https://user-images.githubusercontent.com/6544051/85699456-737abe00-b6d3-11ea-8570-b78353348341.png)
Do you want me to make a PR for this? And do you reckon you could do a another Alpha release with this fix today?

**Comment by IeuanWalker** [comment]
@matteobortolazzo PR created - #108

**Comment by matteobortolazzo** [comment]
v5 Released
