### ISSUE TITLE
Custom Font not getting applied in Xamarin.forms.

### ISSUE THREAD

**Issue by DnyaneshwarWadghanePM** [matteobortolazzo/HtmlLabelPlugin#3]
hi,
I am using this plugin for showing html content in Label but it not picking my custom font. I am using FontFamily property for setting the font. Any other property available for custom font or need change in renderer please suggest.

Thanks in advance.

**Comment by matteobortolazzo** [comment]
Hi,
I know there's this issue, I think it is because if you render HTML the font is specified in the HTML so the label skips the FontFamily property. Try to wrap your HTML into a <div style="font-family='some-font'">YOUR HTML CONTENT</div>. If it works I'll try to update my plugin, wrapping automatically the content in the div if the FontFamily property is specified.

**Comment by DnyaneshwarWadghanePM** [comment]
Thanks for the reply @matteobortolazzo .
It is picking font when I apply following code.
"<div style=\"font-family:HelvLight;\">"+ <b>some text </b>+"</div>" 
but bold label tag is not working

**Comment by matteobortolazzo** [comment]
Are you using `<strong>text</strong>`?

**Comment by DnyaneshwarWadghanePM** [comment]
yes, also tried with <strong> tag but no luck.

**Comment by matteobortolazzo** [comment]
Is it working without the font-family change? I need to investigate but last time I used the plugin bold was working.

**Comment by DnyaneshwarWadghanePM** [comment]
yes, but I want to render content with the specified font.

**Comment by matteobortolazzo** [comment]
Sorry for the late answer, maybe the bold version of your font is not installed. It's an HTML issue.

**Comment by matteobortolazzo** [comment]
During the holidays I'll update the font thing. I close this this issue.
